Because the program output success for both tests that means neither ran into a bug, therefore it works as expected.